// Cache for KeyframeIndex (V4_PLAN.md "Keyframe index"): packs a sorted
// number[] of keyframe seconds as raw little-endian Float64s — plain binary
// rather than JSON, since a two-hour film can carry a few thousand entries
// and this is read on every copy-tier play once the engine (phase 2) lands.

import { prisma } from "@/lib/db";

/** Same identity shape as PlayLog (see prisma/schema.prisma's KeyframeIndex
 *  doc comment): "film" | "scene" match video-cache.ts's MediaKind,
 *  "episode" covers EpisodeFile, which isn't wired into MediaKind yet. */
export type KeyframeKind = "film" | "episode" | "scene";

export type KeyframeSource = "cues" | "ffprobe";

export interface KeyframeCacheKey {
  mtimeMs: number;
  sizeBytes: bigint;
}

export interface KeyframeIndexData {
  keyframeSecs: number[];
  source: KeyframeSource;
}

const FLOAT64_BYTES = 8;

// Plain Uint8Array/DataView rather than node:buffer's Buffer: Prisma's
// generated Bytes type is `Uint8Array<ArrayBuffer>` specifically, and a
// Buffer's backing store is typed as the wider ArrayBufferLike (it could in
// principle be a SharedArrayBuffer), which doesn't structurally match.

/** Pack sorted keyframe seconds as consecutive little-endian Float64s. */
export function packKeyframeSecs(keyframeSecs: number[]): Uint8Array<ArrayBuffer> {
  const arrayBuffer = new ArrayBuffer(keyframeSecs.length * FLOAT64_BYTES);
  const view = new DataView(arrayBuffer);
  for (let i = 0; i < keyframeSecs.length; i++) {
    view.setFloat64(i * FLOAT64_BYTES, keyframeSecs[i], true);
  }
  return new Uint8Array(arrayBuffer);
}

/** Inverse of packKeyframeSecs. Throws on data whose length isn't a
 *  multiple of 8 — that's a corrupt row, not a value worth guessing at. */
export function unpackKeyframeSecs(data: Uint8Array): number[] {
  if (data.length % FLOAT64_BYTES !== 0) {
    throw new Error(`KeyframeIndex.data length ${data.length} is not a multiple of ${FLOAT64_BYTES}`);
  }
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
  const count = data.length / FLOAT64_BYTES;
  const secs = new Array<number>(count);
  for (let i = 0; i < count; i++) {
    secs[i] = view.getFloat64(i * FLOAT64_BYTES, true);
  }
  return secs;
}

/**
 * Load a cached index, or null when there is none or it's stale (source
 * file's mtime/size have moved on since it was built — the same cache-key
 * shape the scanner already uses for Version/EpisodeFile probing).
 */
export async function loadKeyframeIndex(
  kind: KeyframeKind,
  fileId: number,
  current: KeyframeCacheKey,
): Promise<KeyframeIndexData | null> {
  const row = await prisma.keyframeIndex.findUnique({ where: { kind_fileId: { kind, fileId } } });
  if (!row) return null;
  if (row.mtimeMs !== current.mtimeMs || row.sizeBytes !== current.sizeBytes) return null;
  return { keyframeSecs: unpackKeyframeSecs(row.data), source: row.source as KeyframeSource };
}

/** Upsert the cached index for (kind, fileId). */
export async function saveKeyframeIndex(
  kind: KeyframeKind,
  fileId: number,
  current: KeyframeCacheKey,
  data: KeyframeIndexData,
): Promise<void> {
  const packed = packKeyframeSecs(data.keyframeSecs);
  await prisma.keyframeIndex.upsert({
    where: { kind_fileId: { kind, fileId } },
    create: {
      kind,
      fileId,
      mtimeMs: current.mtimeMs,
      sizeBytes: current.sizeBytes,
      source: data.source,
      count: data.keyframeSecs.length,
      data: packed,
    },
    update: {
      mtimeMs: current.mtimeMs,
      sizeBytes: current.sizeBytes,
      source: data.source,
      count: data.keyframeSecs.length,
      data: packed,
    },
  });
}
